version: '3'
services:
  app:
    container_name: FastAPI
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    env_file:
      - .env
  db:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
volumes:
  postgres_data:
    
